# STA326 Assignment 1: Data Collection
This is an assignment that is openly available for the Data Science Practice (STA326). 

The assignment encapsulates a holistic approach towards data collection and analysis, covering a spectrum of data formats and sources. Our objective is to amass, process, and scrutinize data to unearth significant insights. The methodology is sectioned into four pivotal tasks: 
- Web scraping 
- JSON file analysis 
- Working with CSV files
- Data Cleaning

In [2]:
# Imports
import requests  # send request
from bs4 import BeautifulSoup  # parse web pages
import pandas as pd  # csv
from time import sleep  # wait
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import json

## Part 1: Web Scraping

In this assignment, we will explore web scraping, which can often include diverse information from website, and also use the data for simple analysis. We take [douban](https://movie.douban.com/top250) as the target website in this assignment.

### Scraping Rules

1) If you are using another organization's website for scraping, make sure to check the website's terms & conditions. 

2) Do not request data from the website too aggressively (quickly) with your program (also known as spamming), as this may break the website. Make sure your program behaves in a reasonable manner (i.e. acts like a human). One request for one webpage per second is good practice.

3) The layout of a website may change from time to time. Because of this, if you're scraping a website, make sure to revisit the site and rewrite your code as needed.

### 1a) Web Scrape

In order to extract the data we want, we’ll start with extracting the whole web.

In [2]:
# Define a request header (to prevent anti-scraping)
headers = {
    'authority': 'curlconverter.com',
    'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
    'cache-control': 'max-age=0',
    'if-modified-since': 'Fri, 15 Jul 2022 21:44:42 GMT',
    'if-none-match': 'W/"62d1dfca-3a58"',
    'referer': 'https://curlconverter.com/',
    'sec-ch-ua': '" Not A;Brand";v="99", "Chromium";v="102", "Microsoft Edge";v="102"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Linux"',
    'sec-fetch-dest': 'document',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-site': 'cross-site',
    'sec-fetch-user': '?1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.30',
}

This process can be split into three steps:

1. Make a variable called `url`, that stores the following URL (as a string):
https://movie.douban.com/top250?start=0

2. Now, to open the URL, use `requests.get()` and provide `url` and `headers` as its input. Store this in a variable called `page`.

3. After that, make a variable called `soup` to parse the HTML using `BeautifulSoup`. Consider that there will be a method from `BeautifulSoup` that you'll need to call on to get the content from the page.

In [31]:
# YOUR CODE HERE
url = 'http://bang.dangdang.com/books/bestsellers/01.00.00.00.00.00-recent7-0-0-1-1'
page = requests.get(url)
# page = requests.get(url)
soup = BeautifulSoup(page.text)

# raise NotImplementedError()

In [32]:
assert url
assert page
assert soup

In [35]:
soup2 = soup.find('ul', class_ = "bang_list clearfix bang_list_mode")
soup2

<ul class="bang_list clearfix bang_list_mode">
<li>
<div class="list_num red">1.</div>
<div class="pic"><a href="http://product.dangdang.com/23636135.html" target="_blank"><img alt="我们生活在巨大的差距里（余华十年杂文集）" src="http://img3m5.ddimg.cn/83/17/23636135-1_l_1703559193.jpg" title="我们生活在巨大的差距里（余华十年杂文集）"/></a></div>
<div class="name"><a href="http://product.dangdang.com/23636135.html" target="_blank" title="我们生活在巨大的差距里（余华十年杂文集）">我们生活在巨大的差距里（余华十年杂文集）</a></div>
<div class="star"><span class="level"><span style="width: 94.2%;"></span></span><a href="http://product.dangdang.com/23636135.html?point=comment_point" target="_blank">174606条评论</a><span class="tuijian">99.9%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=余华" target="_blank" title="余华作品">余华</a>作品</div>
<div class="publisher_info"><span>2015-01-01</span> <a href="http://search.dangdang.com/?key=北京十月文艺出版社" target="_blank">北京十月文艺出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥17.50</span>
<span class="price_r">¥35.00</span>
            (<span class="price_s">5.0折</span>)
                    </p>
<p class="price_e">电子书：<span class="price_n">¥21.65</span></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('23636135');" name="">加入购物车</a>
<a class="listbtn_buydz" href="http://product.dangdang.com/1901109322.html" name="" target="_blank">购买电子书</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_23636135',encodeURIComponent('23636135&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_23636135" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num red">2.</div>
<div class="pic"><a href="http://product.dangdang.com/25230589.html" target="_blank"><img alt="读读童谣和儿歌（共四册）一年级下册 语文教科书配套书目 人教版快乐读书吧" src="http://img3m9.ddimg.cn/43/30/25230589-1_l_1693895992.jpg" title="读读童谣和儿歌（共四册）一年级下册 语文教科书配套书目 人教版快乐读书吧"/></a></div>
<div class="name"><a href="http://product.dangdang.com/25230589.html" target="_blank" title="读读童谣和儿歌（共四册）一年级下册 语文教科书配套书目 人教版快乐读书吧">读读童谣和儿歌（共四册）一年级下册 语文教科书配套书目 人教版<span class="dot">...</span></a></div>
<div class="star"><span class="level"><span style="width: 93.8%;"></span></span><a href="http://product.dangdang.com/25230589.html?point=comment_point" target="_blank">352060条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=曹文轩" target="_blank" title="曹文轩 陈先云 主编">曹文轩</a> <a href="http://search.dangdang.com/?key=陈先云" target="_blank" title="曹文轩 陈先云 主编">陈先云</a> 主编</div>
<div class="publisher_info"><span>2018-01-01</span> <a href="http://search.dangdang.com/?key=人民教育出版社" target="_blank">人民教育出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥19.10</span>
<span class="price_r">¥39.80</span>
            (<span class="price_s">4.8折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('25230589');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_25230589',encodeURIComponent('25230589&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_25230589" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num red">3.</div>
<div class="pic"><a href="http://product.dangdang.com/29444606.html" target="_blank"><img alt="快乐就是哈哈哈哈哈" src="http://img3m6.ddimg.cn/26/6/29444606-1_l_1691564901.jpg" title="快乐就是哈哈哈哈哈"/></a></div>
<div class="name"><a href="http://product.dangdang.com/29444606.html" target="_blank" title="快乐就是哈哈哈哈哈">快乐就是哈哈哈哈哈</a></div>
<div class="star"><span class="level"><span style="width: 92.6%;"></span></span><a href="http://product.dangdang.com/29444606.html?point=comment_point" target="_blank">62093条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=梁实秋" target="_blank" title="梁实秋 著  时代华语 出品">梁实秋</a> 著  <a href="http://search.dangdang.com/?key=时代华语" target="_blank" title="梁实秋 著  时代华语 出品">时代华语</a> 出品</div>
<div class="publisher_info"><span>2022-08-01</span> <a href="http://search.dangdang.com/?key=中国友谊出版公司" target="_blank">中国友谊出版公司</a></div>
<div class="price">
<p>
<span class="price_n">¥19.80</span>
<span class="price_r">¥52.00</span>
            (<span class="price_s">3.8折</span>)
                    </p>
<p class="price_e">电子书：<span class="price_n">¥39.99</span></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('29444606');" name="">加入购物车</a>
<a class="listbtn_buydz" href="http://product.dangdang.com/1901303817.html" name="" target="_blank">购买电子书</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_29444606',encodeURIComponent('29444606&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_29444606" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">4.</div>
<div class="pic"><a href="http://product.dangdang.com/26483831.html" target="_blank"><img alt="一起长大的玩具 二年级下册 语文教科书配套书目 人教版快乐读书吧" src="http://img3m1.ddimg.cn/44/8/26483831-1_l_1693895757.jpg" title="一起长大的玩具 二年级下册 语文教科书配套书目 人教版快乐读书吧"/></a></div>
<div class="name"><a href="http://product.dangdang.com/26483831.html" target="_blank" title="一起长大的玩具 二年级下册 语文教科书配套书目 人教版快乐读书吧">一起长大的玩具 二年级下册 语文教科书配套书目 人教版快乐读书吧<span class="dot">...</span></a></div>
<div class="star"><span class="level"><span style="width: 95.6%;"></span></span><a href="http://product.dangdang.com/26483831.html?point=comment_point" target="_blank">190416条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=曹文轩" target="_blank" title="曹文轩 陈先云 主编">曹文轩</a> <a href="http://search.dangdang.com/?key=陈先云" target="_blank" title="曹文轩 陈先云 主编">陈先云</a> 主编</div>
<div class="publisher_info"><span>2019-01-01</span> <a href="http://search.dangdang.com/?key=人民教育出版社" target="_blank">人民教育出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥7.70</span>
<span class="price_r">¥16.00</span>
            (<span class="price_s">4.8折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('26483831');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_26483831',encodeURIComponent('26483831&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_26483831" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">5.</div>
<div class="pic"><a href="http://product.dangdang.com/26916249.html" target="_blank"><img alt="中国古代寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧" src="http://img3m9.ddimg.cn/30/7/26916249-1_l_1706233885.jpg" title="中国古代寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧"/></a></div>
<div class="name"><a href="http://product.dangdang.com/26916249.html" target="_blank" title="中国古代寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧">中国古代寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧</a></div>
<div class="star"><span class="level"><span style="width: 92.8%;"></span></span><a href="http://product.dangdang.com/26916249.html?point=comment_point" target="_blank">112186条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=曹文轩" target="_blank" title="曹文轩、陈先云 主编">曹文轩</a>、<a href="http://search.dangdang.com/?key=陈先云" target="_blank" title="曹文轩、陈先云 主编">陈先云</a> 主编</div>
<div class="publisher_info"><span>2019-01-01</span> <a href="http://search.dangdang.com/?key=人民教育出版社" target="_blank">人民教育出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥12.00</span>
<span class="price_r">¥25.00</span>
            (<span class="price_s">4.8折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('26916249');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_26916249',encodeURIComponent('26916249&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_26916249" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">6.</div>
<div class="pic"><a href="http://product.dangdang.com/27878108.html" target="_blank"><img alt="额尔古纳河右岸（茅盾文学奖获奖作品全集28）" src="http://img3m8.ddimg.cn/5/14/27878108-1_l_1703749538.jpg" title="额尔古纳河右岸（茅盾文学奖获奖作品全集28）"/></a></div>
<div class="name"><a href="http://product.dangdang.com/27878108.html" target="_blank" title="额尔古纳河右岸（茅盾文学奖获奖作品全集28）">额尔古纳河右岸（茅盾文学奖获奖作品全集28）</a></div>
<div class="star"><span class="level"><span style="width: 96.8%;"></span></span><a href="http://product.dangdang.com/27878108.html?point=comment_point" target="_blank">794478条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=迟子建" target="_blank" title="迟子建">迟子建</a></div>
<div class="publisher_info"><span>2019-06-01</span> <a href="http://search.dangdang.com/?key=人民文学出版社" target="_blank">人民文学出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥16.00</span>
<span class="price_r">¥32.00</span>
            (<span class="price_s">5.0折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('27878108');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_27878108',encodeURIComponent('27878108&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_27878108" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">7.</div>
<div class="pic"><a href="http://product.dangdang.com/21055821.html" target="_blank"><img alt="我与地坛（纪念版）（2024年百班千人寒假书单 九年级推荐阅读）" src="http://img3m1.ddimg.cn/6/9/21055821-1_l_1703840299.jpg" title="我与地坛（纪念版）（2024年百班千人寒假书单 九年级推荐阅读）"/></a></div>
<div class="name"><a href="http://product.dangdang.com/21055821.html" target="_blank" title="我与地坛（纪念版）（2024年百班千人寒假书单 九年级推荐阅读）">我与地坛（纪念版）（2024年百班千人寒假书单 九年级推荐阅读）</a></div>
<div class="star"><span class="level"><span style="width: 93.6%;"></span></span><a href="http://product.dangdang.com/21055821.html?point=comment_point" target="_blank">1162595条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=史铁生" target="_blank" title="史铁生">史铁生</a></div>
<div class="publisher_info"><span>2011-06-01</span> <a href="http://search.dangdang.com/?key=人民文学出版社" target="_blank">人民文学出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥16.20</span>
<span class="price_r">¥29.00</span>
            (<span class="price_s">5.6折</span>)
                    </p>
<p class="price_e">电子书：<span class="price_n">¥9.99</span></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('21055821');" name="">加入购物车</a>
<a class="listbtn_buydz" href="http://product.dangdang.com/1901115315.html" name="" target="_blank">购买电子书</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_21055821',encodeURIComponent('21055821&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_21055821" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">8.</div>
<div class="pic"><a href="http://product.dangdang.com/26916248.html" target="_blank"><img alt="克雷洛夫寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧" src="http://img3m8.ddimg.cn/29/6/26916248-1_l_1693895868.jpg" title="克雷洛夫寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧"/></a></div>
<div class="name"><a href="http://product.dangdang.com/26916248.html" target="_blank" title="克雷洛夫寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧">克雷洛夫寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧</a></div>
<div class="star"><span class="level"><span style="width: 93.8%;"></span></span><a href="http://product.dangdang.com/26916248.html?point=comment_point" target="_blank">97668条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=曹文轩" target="_blank" title="曹文轩、陈先云 主编">曹文轩</a>、<a href="http://search.dangdang.com/?key=陈先云" target="_blank" title="曹文轩、陈先云 主编">陈先云</a> 主编</div>
<div class="publisher_info"><span>2019-01-01</span> <a href="http://search.dangdang.com/?key=人民教育出版社" target="_blank">人民教育出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥12.00</span>
<span class="price_r">¥25.00</span>
            (<span class="price_s">4.8折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('26916248');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_26916248',encodeURIComponent('26916248&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_26916248" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">9.</div>
<div class="pic"><a href="http://product.dangdang.com/29504472.html" target="_blank"><img alt="经典常谈 朱自清著八年级下册语文教材名著导读推荐阅读书目 适合学生自主阅读的课外阅读读本 一部讲述中国传统经典文化的著作" src="http://img3m2.ddimg.cn/96/6/29504472-1_l_20.jpg" title="经典常谈 朱自清著八年级下册语文教材名著导读推荐阅读书目 适合学生自主阅读的课外阅读读本 一部讲述中国传统经典文化的著作"/></a></div>
<div class="name"><a href="http://product.dangdang.com/29504472.html" target="_blank" title="经典常谈 朱自清著八年级下册语文教材名著导读推荐阅读书目 适合学生自主阅读的课外阅读读本 一部讲述中国传统经典文化的著作">经典常谈 朱自清著八年级下册语文教材名著导读推荐阅读书目 适合<span class="dot">...</span></a></div>
<div class="star"><span class="level"><span style="width: 88.6%;"></span></span><a href="http://product.dangdang.com/29504472.html?point=comment_point" target="_blank">67079条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=朱自清" target="_blank" title="朱自清">朱自清</a></div>
<div class="publisher_info"><span>2023-01-01</span> <a href="http://search.dangdang.com/?key=南方出版社" target="_blank">南方出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥10.80</span>
<span class="price_r">¥26.80</span>
            (<span class="price_s">4.0折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('29504472');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_29504472',encodeURIComponent('29504472&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_29504472" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">10.</div>
<div class="pic"><a href="http://product.dangdang.com/26916247.html" target="_blank"><img alt="伊索寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧" src="http://img3m7.ddimg.cn/28/5/26916247-1_l_1693895869.jpg" title="伊索寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧"/></a></div>
<div class="name"><a href="http://product.dangdang.com/26916247.html" target="_blank" title="伊索寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧">伊索寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧</a></div>
<div class="star"><span class="level"><span style="width: 94.2%;"></span></span><a href="http://product.dangdang.com/26916247.html?point=comment_point" target="_blank">87091条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=曹文轩" target="_blank" title="曹文轩、陈先云 主编">曹文轩</a>、<a href="http://search.dangdang.com/?key=陈先云" target="_blank" title="曹文轩、陈先云 主编">陈先云</a> 主编</div>
<div class="publisher_info"><span>2019-01-01</span> <a href="http://search.dangdang.com/?key=人民教育出版社" target="_blank">人民教育出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥12.00</span>
<span class="price_r">¥25.00</span>
            (<span class="price_s">4.8折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('26916247');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_26916247',encodeURIComponent('26916247&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_26916247" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">11.</div>
<div class="pic"><a href="http://product.dangdang.com/25283736.html" target="_blank"><img alt="呼兰河传(《语文》推荐阅读丛书)人民文学出版社" src="http://img3m6.ddimg.cn/27/8/25283736-1_l_7.jpg" title="呼兰河传(《语文》推荐阅读丛书)人民文学出版社"/></a></div>
<div class="name"><a href="http://product.dangdang.com/25283736.html" target="_blank" title="呼兰河传(《语文》推荐阅读丛书)人民文学出版社">呼兰河传(《语文》推荐阅读丛书)人民文学出版社</a></div>
<div class="star"><span class="level"><span style="width: 98.4%;"></span></span><a href="http://product.dangdang.com/25283736.html?point=comment_point" target="_blank">193154条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=萧红" target="_blank" title="萧红">萧红</a></div>
<div class="publisher_info"><span>2018-04-01</span> <a href="http://search.dangdang.com/?key=人民文学出版社" target="_blank">人民文学出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥13.00</span>
<span class="price_r">¥26.00</span>
            (<span class="price_s">5.0折</span>)
                    </p>
<p class="price_e">电子书：<span class="price_n">¥13.00</span></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('25283736');" name="">加入购物车</a>
<a class="listbtn_buydz" href="http://product.dangdang.com/1901270962.html" name="" target="_blank">购买电子书</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_25283736',encodeURIComponent('25283736&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_25283736" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">12.</div>
<div class="pic"><a href="http://product.dangdang.com/23197949.html" target="_blank"><img alt="呼兰河传(中小学生课外阅读指导丛书) 无障碍阅读 彩插励志版 180000多名读者热评！" src="http://img3m9.ddimg.cn/71/22/23197949-1_l_42.jpg" title="呼兰河传(中小学生课外阅读指导丛书) 无障碍阅读 彩插励志版 180000多名读者热评！"/></a></div>
<div class="name"><a href="http://product.dangdang.com/23197949.html" target="_blank" title="呼兰河传(中小学生课外阅读指导丛书) 无障碍阅读 彩插励志版 180000多名读者热评！">呼兰河传(中小学生课外阅读指导丛书) 无障碍阅读 彩插励志版 180<span class="dot">...</span></a></div>
<div class="star"><span class="level"><span style="width: 98.4%;"></span></span><a href="http://product.dangdang.com/23197949.html?point=comment_point" target="_blank">305045条评论</a><span class="tuijian">100%推荐</span></div>
<div class="publisher_info"><a href="http://search.dangdang.com/?key=萧红" target="_blank" title="萧红">萧红</a></div>
<div class="publisher_info"><span>2021-05-01</span> <a href="http://search.dangdang.com/?key=南方出版社" target="_blank">南方出版社</a></div>
<div class="price">
<p>
<span class="price_n">¥7.10</span>
<span class="price_r">¥15.80</span>
            (<span class="price_s">4.5折</span>)
                    </p>
<p class="price_e"></p>
<div class="buy_button">
<a class="listbtn_buy" ddname="加入购物车" href="javascript:AddToShoppingCart('23197949');" name="">加入购物车</a>
<a class="listbtn_collect" ddname="加入收藏" href="javascript:showMsgBox('addto_favorlist_23197949',encodeURIComponent('23197949&amp;platform=3'), 'http://myhome.dangdang.com/addFavoritepop');" id="addto_favorlist_23197949" name="">收藏</a>
</div>
</div>
</li>
<li>
<div class="list_num">13.</div>
<div class="pic"><a href="http://product.dangdang.com/28488175.html" target="_blank"><img alt="神笔马良 二年级下册 语文教科书配套书目 人教版快乐读书吧" src="http://img3m5.ddimg.cn/34/25/28488175-1_l_1708934210.jpg" title="神笔马良 二年级下册 语文教科书配套书目 人教版快乐读书吧"/></a></div>
<div class="name"><a href="http://product.dangdang.com/28488175.html" target="_blank" title="神笔马良 二年级下册 语文教科书配套书目 人教版快乐读书吧">神笔马良 二年级下册 语文教科书配套书目 人教版快乐读书吧</a></div>
<div class="star"><span class="level"><span style="width: 95.4%;"></span></span><a href="http://product.dangdang.com/28488175.html?point=comment_point" target="_blank">157474条评论</a><span class="tuijian">100%推荐</span></div>

In [146]:
for li in soup2.find_all('div', class_ = "price"):
#     print(li)
    print(li.find_all('span', class_ = "price_s")[0].string)

5.0折
4.8折
3.8折
4.8折
4.8折
5.0折
5.6折
4.8折
4.0折
4.8折
5.0折
4.5折
4.8折
4.8折
4.8折
7.0折
6.5折
4.6折
6.9折
5.0折

### 1b) Data Extraction

Extract the data (`name` and `star`) from the page and save it in the corresponding list like `movie_name` and `movie_star`. 

Make sure you extract it as a string.

To do so, you have to use the soup object created in the above cell.

**Hint**: from your soup variable, you can access this with `soup.select()`

In [69]:
movie_name = []  # movie name
movie_star = []  # movie star----- I used discount of the books instead, 
##since the stars of the books are all full mark.

for li in soup2.find_all('div', class_ = "name"):
    print(li.find_all('a')[0]['title'])
    movie_name.append(li.find_all('a')[0]['title'])
for li in soup2.find_all('div', class_ = "price"):
    print(li.find_all('span', class_ = "price_s")[0].string)
    movie_star.append(li.find_all('span', class_ = "price_s")[0].string)
    
# soup.select("")
# YOUR CODE HERE
# raise NotImplementedError()

我们生活在巨大的差距里（余华十年杂文集）
读读童谣和儿歌（共四册）一年级下册 语文教科书配套书目 人教版快乐读书吧
快乐就是哈哈哈哈哈
一起长大的玩具 二年级下册 语文教科书配套书目 人教版快乐读书吧
中国古代寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧
额尔古纳河右岸（茅盾文学奖获奖作品全集28）
我与地坛（纪念版）（2024年百班千人寒假书单 九年级推荐阅读）
克雷洛夫寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧
经典常谈 朱自清著八年级下册语文教材名著导读推荐阅读书目 适合学生自主阅读的课外阅读读本 一部讲述中国传统经典文化的著作
伊索寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧
呼兰河传(《语文》推荐阅读丛书)人民文学出版社
呼兰河传(中小学生课外阅读指导丛书) 无障碍阅读 彩插励志版 180000多名读者热评！
神笔马良 二年级下册 语文教科书配套书目 人教版快乐读书吧
大头儿子和小头爸爸 二年级下册 语文教科书配套书目 人教版快乐读书吧
七色花 二年级下册 语文教科书配套书目 人教版快乐读书吧
认知破局 怎样突破能力、视野和人脉 全民商业导师张琦给大家的人生破局指南
红楼梦原著版（上、下册，全两册，全本120回）（团购电话:400-1066666转6）
病隙碎笔 2021纪念版（史铁生充满灵性光辉的生命笔记，启迪无数读者的长篇哲思散文经典）
活着（余华代表作，精装，易烊千玺推荐阅读）
俗世奇人（足本）（《语文》推荐阅读丛书）人民文学出版社
5.0折
4.8折
3.8折
4.8折
4.8折
5.0折
5.6折
4.8折
4.0折
4.8折
5.0折
4.5折
4.8折
4.8折
4.8折
7.0折
6.5折
4.6折
6.9折
5.0折

### 1c) Collecting into a dataframe

Create a dataframe `movie_df` and add the data from the lists above to it. 
- `movie_name` is the movie name. Set the column name as `movie name`
- `movie_star` is the population estimate via star. Add it to the dataframe, and set the column name as `movie star`

Make sure to check the head of your dataframe to see that everything looks right! ie: movie_df.head()

Finally, you should save the DataFrame to a csv file under this folder`'./output'`.

In [93]:
csv_name =  "MovieDouban.csv"
csv_dir = "./output"
# # YOUR CODE HERE
data_list = pd.DataFrame({'name':movie_name,'discount':movie_star})
data_list.to_csv(csv_dir+'/'+csv_name,index = False)
data_list.head()
# raise NotImplementedError()

                                   name discount
0                  我们生活在巨大的差距里（余华十年杂文集）     5.0折
1  读读童谣和儿歌（共四册）一年级下册 语文教科书配套书目 人教版快乐读书吧     4.8折
2                             快乐就是哈哈哈哈哈     3.8折
3      一起长大的玩具 二年级下册 语文教科书配套书目 人教版快乐读书吧     4.8折
4       中国古代寓言 三年级下册 语文教科书配套书目 人教版快乐读书吧     4.8折

## Part 2: JSON File Analysis

After the initial phase of web scraping, we transition to analyzing pre-collected data, which is often stored in accessible and structured formats like JSON and CSV. This approach allows us to bypass the time-consuming process of data collection through web scraping for certain datasets that are already available, enabling us to dive directly into data analysis.

### Overview
In the section, you will first be working with a file called 'anon_user_dat.json'. You can find the given data under the folder `'./data/data_identifying'`. This file contains information about some (fake) Tinder users. When creating an account, each Tinder user was asked to provide their first name, last name, work email (to verify the disclosed workplace), age, gender, phone # and zip code. Before releasing this data, a data scientist cleaned the data to protect the privacy of Tinder's users by removing the obvious personal identifiers: phone #, zip code, and IP address. However, the data scientist chose to keep each users' email addresses because when they visually skimmed a couple of the email addresses none of them seemed to have any of the users' actual names in them. This is where the data scientist made a huge mistake!

Data Files:
- anon_user_dat.json
- employee_info.json


We will take advantage of having the work email addresses by finding the employee information of different companies and matching that employee information with the information we have, in order to identify the names of the secret Tinder users!

### 2a) Load data from JSON file 

Load the `anon_user_dat.json` json file into a pandas dataframe. Call it `df_personal`.

In [112]:
# YOUR CODE HERE
df_personal = pd.read_json('./data/data_identifying/anon_user_dat.json')
df_personal.head()
# raise NotImplementedError()

   age                        email  gender
0   60  gshoreson0@seattletimes.com    Male
1   47           eweaben1@salon.com  Female
2   27      akillerby2@gravatar.com    Male
3   46            gsainz3@zdnet.com    Male
4   72     bdanilewicz4@4shared.com    Male

In [87]:
assert isinstance(df_personal, pd.DataFrame)

### 2b) Check the first 10 emails 

Save the first 10 emails to a Series, and call it `sample_emails`. 
You should then print out this Series. ( Use print() )

The purpose of this is to get a sense of how these work emails are structured and how we could possibly extract where each anonymous user seems to work.

In [98]:
# YOUR CODE HERE
sample_emails = df_personal.head(10)['email']
sample_emails
# raise NotImplementedError()

0    gshoreson0@seattletimes.com
1             eweaben1@salon.com
2        akillerby2@gravatar.com
3              gsainz3@zdnet.com
4       bdanilewicz4@4shared.com
5      sdeerness5@wikispaces.com
6         jstillwell6@ustream.tv
7         mpriestland7@opera.com
8       nerickssen8@hatena.ne.jp
9             hparsell9@xing.com
Name: email, dtype: object

In [99]:
assert isinstance(sample_emails, pd.Series)

### 2c) Extract the Company Name From the Email 

Create a function with the following specifications:
- Function Name: extract_company
- Purpose: to extract the company of the email (i.e., everything after the @ sign but before the first .)
- Parameter(s): email (string)
- Returns: The extracted part of the email (string)
- Hint: This should take 1 line of code. Look into the find('') method. 

You can start with this outline:
```python 
def extract_company(email):
    return
```

Example Usage: 
- extract_company("larhe@uber.com") should return "uber"
- extract_company(“ds@cogs.edu”) should return “cogs”

In [110]:
# YOUR CODE HERE
def extract_company(email):
    a = email.find('@')
    b = email.find('.')
    return email[a+1:b]
print(extract_company('larhe@uber.com'))
# raise NotImplementedError()

uber

In [111]:
assert extract_company("gshoreson0@seattletimes.com") == "seattletimes"
assert extract_company("amcgeffen1d@goo.ne.jp") == 'goo'

With a little bit of basic sleuthing (aka googling) and web-scraping (aka selectively reading in html code) it turns out that you've been able to collect information about all the present employees/interns of the companies you are interested in. Specifically, on each company website, you have found the name, gender, and age of its employees. You have saved that info in employee_info.json and plan to see if, using this new information, you can match the Tinder accounts to actual names.

### 2d) Load in employee data 

Load the json file into a pandas dataframe. Call it `df_employee`.

In [114]:
# YOUR CODE HERE
df_employee = pd.read_json('./data/data_identifying/employee_info.json')
df_employee.head()
# raise NotImplementedError()

   company first_name last_name  gender  age
0  123-reg  Inglebert  Falconer    Male   42
1      163     Rafael  Bedenham    Male   14
2      163     Lemuel      Lind    Male   31
3      163      Penny   Pennone  Female   45
4      163       Elva  Crighton  Female   52

In [115]:
assert isinstance(df_employee, pd.DataFrame)

### 2e) Match the employee name with company, age, gender 

Create a function with the following specifications:
- Function name: employee_matcher
- Purpose: to match the employee name with the provided company, age, and gender
- Parameter(s): company (string), age (int), gender (string)
- Returns: The employee first_name and last_name like this: return first_name, last_name 
- Note: If there are multiple employees that fit the same description, first_name and last_name should return a list of all possible first names and last names i.e., ['Desmund', 'Kelby'], ['Shepley', 'Tichner']. Note that the names of the individuals that would produce this output are 'Desmund Shepley' and 'Kelby Tichner'.

Hint:
There are many different ways to code this. An inelegant solution is to loop through `df_employee` 
   and for each data item see if the company, age, and gender match
   i.e., 
   ```python
   for i in range(0, len(df_employee)):
             if (company == df_employee.loc[i,'company']):
   ```
   
However! The solution above is very inefficient and long, so you should try to look into this:
Google the df.loc method: It extracts pieces of the dataframe
   if it fulfills a certain condition.
   i.e., 
   
```python
df_employee.loc[df_employee['company'] == company]
```

If you need to convert your pandas data series into a list, you can do ```list(result)``` where result is a pandas "series"

You can start with this outline:
```python
def employee_matcher(company, age, gender):
    return first_name, last_name
```

In [133]:
# YOUR CODE HERE
def employee_matcher(company, age, gender):
    match = df_employee.loc[df_employee['company'] == company].loc[df_employee['age'] == age].loc[df_employee['gender'] == gender]

    first_name = match['first_name'].values
    last_name = match['last_name'].values
    return first_name, last_name
employee_matcher("google", 41, "Male")
# raise NotImplementedError()

(array(['Maxwell'], dtype=object), array(['Jorio'], dtype=object))

In [134]:
assert employee_matcher("google", 41, "Male") == (['Maxwell'], ['Jorio'])
assert employee_matcher("salon", 47, "Female") == (['Elenore'], ['Gravett'])
assert employee_matcher("webmd", 28, "Nonbinary") == (['Zaccaria'], ['Bartosiak'])

### 2f) Extract all the private data 

- Create 2 empty lists called `first_names` and `last_names`
- Loop through all the people we are trying to identify in df_personal
- Call the `extract_company` function (i.e., `extract_company(df_personal.loc[i, 'email'])` )
- Call the `employee_matcher` function 
- Append the results of `employee_matcher` to the appropriate lists (`first_names` and `last_names`)

In [141]:
# YOUR CODE HERE
# raise NotImplementedError()
first_names = []
last_names = []

for i in range(len(df_personal)):
    a,b = employee_matcher(extract_company(df_personal.loc[i, 'email']), df_personal.loc[i]['age'], 
                     df_personal.loc[i]['gender'])
    first_names.append(a)
    last_names.append(b)

In [142]:
assert first_names[45:50]== [['Justino'], ['Tadio'], ['Kennith'], ['Cedric'], ['Amargo']]
assert last_names[45:50] == [['Corro'], ['Blackford'], ['Milton'], ['Yggo'], ['Grigor']]

### 2g) Add the names to the original 'secure' dataset! 

We have done this last step for you below, all you need to do is run this cell.

For your own personal enjoyment, you should also print out the new `df_personal` with the identified people.

In [144]:
df_personal['first_name'] = first_names
df_personal['last_name'] = last_names
df_personal

,age,email,gender,first_name,last_name
0,60,gshoreson0@seattletimes.com,Male,[Gordon],[DelaField]
1,47,eweaben1@salon.com,Female,[Elenore],[Gravett]
2,27,akillerby2@gravatar.com,Male,[Abbe],[Stockdale]
3,46,gsainz3@zdnet.com,Male,[Guido],[Comfort]
4,72,bdanilewicz4@4shared.com,Male,[Brody],[Pinckard]
...,...,...,...,...,...
995,3,pstroulgerrn@time.com,Female,[Penelopa],[Roman]
996,49,kbasnettro@seattletimes.com,Female,"[Anthiathia, Kandy]","[Baldwin, Cossam]"
997,75,pmortlockrp@liveinternet.ru,Male,[Paco],[Weatherburn]
998,81,sphetterq@toplist.cz,Male,[Sammy],[Dymick]
999,70,jtyresrr@slashdot.org,Male,[Josiah],[Ayshford]

## Part 3: Working with CSV Files
Continuing with our exploration of pre-collected data formats, we delve into CSV files, which are renowned for their simplicity and widespread use in representing tabular data. This stage involves leveraging libraries like pandas in Python, which simplify the process of reading, manipulating, and analyzing CSV data. 

### Overview

For this assignment, you are provided with two data files that contain information on a sample of people. The two files and their columns are:

- `age_steps.csv`: Contains one row for each person.
    - `id`: Unique identifier for the person.
    - `age`: Age of the person.
    - `steps`: Number of steps the person took on average in January 2018.
    
    
- `incomes.json`: Contains one record for each person.
    - `id`: Unique identifier for the person. Two records with the same ID between `age_steps.csv` and `incomes.json` correspond to the same person.
    - `last_name`: Last name of the person.
    - `first_name`: First name of the person.
    - `income`: Income of the person in 2018.
    
You can find the given data under the folder `'./data/data_wrangling'`. To finish the assignment, we recommend looking at the official 10 minutes to pandas guide: http://pandas.pydata.org/pandas-docs/stable/10min.html

**Question 3a:** Load the `age_steps.csv` file into a `pandas` DataFrame named `df_steps`. It should have 11257 rows and 3 columns.

In [32]:
# YOUR CODE HERE
df_steps = pd.read_csv('data/data_wrangling/age_steps.csv')
df_steps
# raise NotImplementedError()

          id  age  steps
2018      39   42   9508
3535      53   24   9183
10693     70   47   6314
1464      87   43   6935
315       88   41   8772
...      ...  ...    ...
7982   99943   49   7470
850    99955   49   4774
1457   99967   36   6805
4185   99971   42   7208
11195  99993   32   6893

[11257 rows x 3 columns]

In [4]:
assert isinstance(df_steps, pd.DataFrame)
assert df_steps.shape == (11257, 3)

**Question 3b:** Load the `incomes.json` file into a `pandas` DataFrame called `df_income`. The DataFrame should have 13332 rows and 4 columns. 

Hint: Find a pandas function similar to `read_csv` for JSON files.

In [31]:
# YOUR CODE HERE
df_income = pd.read_json('data/data_wrangling/incomes.json')
df_income
# raise NotImplementedError()

          id  last_name  first_name    income
7378      23      Eaton        John   9724.68
8987      39      Price     Charles  47158.58
1840      53     Butler       Jamie   6989.65
10640     70       King     Natasha  53546.59
9498      87     Fisher     Nicolas   3451.87
...      ...        ...         ...       ...
4745   99954  Hernandez       Diane  10519.62
12359  99955       Lara       Randy  45211.78
11397  99967     Obrien  Kristopher  28285.10
176    99991      Young       Sarah      0.00
9363   99993     Sutton     Kenneth      0.00

[13332 rows x 4 columns]

In [6]:
assert isinstance(df_income, pd.DataFrame)
assert df_income.shape == (13332, 4)

**Question 3c:** Drop the `first_name` and `last_name` columns from the `df_income` DataFrame. The resulting DataFrame should only have two columns.

In [62]:
# YOUR CODE HERE
df_income = df_income.drop(columns = ['first_name','last_name'])
# raise NotImplementedError()

In [63]:
assert 'first_name' not in df_income.columns
assert 'last_name' not in df_income.columns

**Question 3d:** Merge the `df_steps` and `df_income` DataFrames into a single combined DataFrame called `df`. Use the `id` column to match rows together.

The final DataFrame should have 10,135 rows and 4 columns: `id`, `income`, `age`, and `steps`.

Call an appropriate `pandas` method to perform this operation; don't write a `for` loop. (In general, writing a `for` loop for a DataFrame will produce poor results.)

In [64]:
# YOUR CODE HERE
df = pd.merge(df_steps,df_income,on = 'id')
df
# raise NotImplementedError()

          id  age  steps    income
0      36859   48   6764  10056.43
1      99794   39   4308  13869.47
2      33364   36   6410  79634.92
3      73874   35   7870  12369.03
4      66956   56   7670  41150.18
...      ...  ...    ...       ...
10130  42474   28   7307  49128.60
10131  61626   44   7752  20096.38
10132  52336   41     -1      0.00
10133  54972   44   7548  18350.20
10134  17411   43   8765  88965.55

[10135 rows x 4 columns]

In [65]:
assert isinstance(df, pd.DataFrame)
assert set(df.columns) == set(['id', 'income', 'age', 'steps'])
assert df.shape == (10135, 4)

**Question 3e:** Reorder the columns of `df` so that they appear in the order: `id`, `age`, `steps`, then `income`.

(Note: If your DataFrame is already in this order, just put `df` in this cell.)

In [66]:
# YOUR CODE HERE
df.sort_values(by = ['id','age','steps','income'])
# raise NotImplementedError()

          id  age  steps    income
1801      39   42   9508  47158.58
3164      53   24   9183   6989.65
9624      70   47   6314  53546.59
1305      87   43   6935   3451.87
281       88   41   8772  97869.35
...      ...  ...    ...       ...
8545   99933   45   5883  41943.16
7195   99943   49   7470  29343.43
755    99955   49   4774  45211.78
1300   99967   36   6805  28285.10
10079  99993   32   6893      0.00

[10135 rows x 4 columns]

In [22]:
assert list(df.columns) == ['id', 'age', 'steps', 'income']

**Question 3f:** You may have noticed something strange: the merged `df` DataFrame has fewer rows than either of `df_steps` and `df_income`. Why did this happen? (If you're unsure, check out the documentation for the `pandas` method you used to merge these two datasets. Take note of the default values set for this method's parameters.)

Please select the **one** correct explanation below and save your answer in the variable `q1f_answer`. For example, if you believe choice number 4 explains why `df` has fewer rows, set `q1f_answer = 4`.

1. Some steps were recorded inaccurately in `df_steps`.
2. Some incomes were recorded inaccurately in `df_income`.
3. There are fewer rows in `df_steps` than in `df_income`.
4. There are fewer columns in `df_steps` than in `df_income`.
5. Some `id` values in either `df_steps` and `df_income` were missing in the other DataFrame.
6. Some `id` values were repeated in `df_steps` and in `df_income`.

You may use the cell below to run whatever code you want to check the statements above. Just make sure to set `q1f_answer` once you've selected a choice.

In [41]:
# YOUR CODE HERE
df_income.sort_values('id')
df_steps.sort_values('id')
df_inner = pd.merge(df_income,df_steps,how = 'inner',on = 'id')
print(len(df_inner))
df_outer = pd.merge(df_income,df_steps,how = 'outer',on = 'id')
print(len(df_outer))
# raise NotImplementedError()

q1f_answer = 5

10135
14454

In [42]:
assert isinstance(q1f_answer, int)

## Part 4 - Data Cleaning

Post data collection, a pivotal step ensues—Data Cleaning. This phase is crucial for ensuring the reliability and accuracy of our analysis. It involves scrutinizing the data for inaccuracies, inconsistencies, and incompleteness. Techniques such as removing duplicates, handling missing values, and correcting errors are employed to refine the dataset. A common phenomenon is that the collected data may contain missing values. Here are two common ones:

- **Nonresponse.** For example, people might have left a field blank when responding to a survey, or left the entire survey blank.
- **Lost in entry.** Data might have been lost after initial recording. For example, a disk cleanup might accidentally wipe older entries of a database.

In general, it is **not** appropriate to simply drop missing values from the dataset or pretend that if filled in they would not change your results. In 2016, many polls mistakenly predicted that Hillary Clinton would easily win the Presidential election by committing this error. In this particular dataset, however, the **missing values occur completely at random**. This criteria allows us to drop missing values without significantly affecting our conclusions.

In this section, we continue use the data mentioned in Part 3.

**Question 4a:** How many values are missing in the `income` column of `df`? Save this number into a variable called `n_nan`.

In [51]:
# YOUR CODE HERE
n_nan = len(df_income) - len(df_income.dropna(how='any'))
n_nan
# raise NotImplementedError()

587

In [46]:
assert(n_nan)

**Question 4b:** Remove all rows from `df` that have missing values.

In [71]:
# Remove all rows from df that have missing data. In other words, remove all rows with NaN values.

# YOUR CODE HERE
df = df.dropna(how='any')
# raise NotImplementedError()

In [72]:
assert sum(np.isnan(df['income'])) == 0
assert df.shape == (9684, 4)

**Question 4c:** Note that we can now compute the average income. If your `df` variable contains the right values, `df['income'].mean()` should produce the value `25508.84`.

Suppose that we didn't drop the missing incomes. What will running `df['income'].mean()` output? Use the variable `q2c_answer` to record which of the below statements you think is true. As usual, you can use the cell below to run any code you'd like in order to help you answer this question as long as you set `q2c_answer` once you've finished.

1. No change; `df['income'].mean()` will ignore the missing values and output `25508.84`.
2. `df['income'].mean()` will produce an error.
3. `df['income'].mean()` will output `0`.
4. `df['income'].mean()` will output `nan` (not a number).
5. `df['income'].mean()` will fill in the missing values with the average income, then compute the average.
6. `df['income'].mean()` will fill in the missing values with `0`, then compute the average.

In [69]:
# YOUR CODE HERE
# raise NotImplementedError()
# df['income'].mean()
q2c_answer = 1

In [70]:
assert isinstance(q2c_answer, int)

**Question 4d:** Suppose that missing incomes did not occur at random, and that individuals with incomes below \$10000 a year are less likely to report their incomes. If so, which of the following statements below is true? Record your choice in the variable `q2d_answer`.

1. `df['income'].mean()` will likely output a value that is the same as the population's average income
2. `df['income'].mean()` will likely output a value that is smaller than the population's average income.
3. `df['income'].mean()` will likely output a value that is larger than the population's average income.
4. `df['income'].mean()` will raise an error.

In [73]:
# YOUR CODE HERE
# raise NotImplementedError()
q2d_answer = 3

In [74]:
assert isinstance(q2d_answer, int)

## Complete!

Congrats, you're done!